language: ruby
bundler_args: --without guard metrics
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
notifications:
  email:
    - mbj@seonic.net
